[HANGING_MAN]
BODY = 15.0
HEIGHT = 75.0

[SHOOTING_STAR]
HEIGHT = 25.0

[SPINNING_TOP]
MIN = 40.0
MAX = 60.0

[MARUBOZU]
MATCH = 98.0

[ENGULFING]
FACTOR = 1.1

[MORNING_STAR]
PREV2_BODY = 90.0
PREV_BODY = 10.0

[TWEEZER]
BODY = 15.0
HL = 0.01
TOP_BODY = 40.0
BOTTOM_BODY = 60.0
